version: '3.8'

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - backend-data:/app/data
      - backend-uploads:/app/uploads
    networks:
      - app-network

  frontend:
    build:
      context: ./my-ts-react-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
  backend-uploads:

